### ISSUE TITLE
code does not work even after u install browserify

### ISSUE THREAD

**Issue by hiteshtara** [jhartikainen/react-chat-app#1]
react-chat@0.0.0 build /root/research-coi/react-chat-app

> browserify -t [ babelify --presets [ es2015 react ] ] src/index.js -o build/app.js

/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by jhartikainen** [comment]
Did you check the file pointed out by the error? 

Either way, this seems to indicate that you're missing the `node` executable in your path.

**Comment by hiteshtara** [comment]
react-chat@0.0.0 build /root/react-chat-app

> browserify -t [ babelify --presets [ es2015 react ] ] src/index.js -o build/app.js

Error: Cannot find module 'simple-peer' from '/root/react-chat-app/src'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! react-chat@0.0.0 build: `browserify -t [ babelify --presets [ es2015 react ] ] src/index.js -o build/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-chat@0.0.0 build script 'browserify -t [ babelify --presets [ es2015 react ] ] src/index.js -o build/app.js'.
npm ERR! This is most likely a problem with the react-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -t [ babelify --presets [ es2015 react ] ] src/index.js -o build/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/react-chat-app/npm-debug.log

Hi ,
thanks for replying npm run build command gives this error I have run several node applications but I cannot figure out this one

**Comment by adampasz** [comment]
I'm having the same problem.  Clean install, when I try to run your browserify command from the shell, it returns this...

```
$ browserify -t [ babelify --presets [react]] src/app.js -o build/app.js                                    
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({},{},[]);
```

For some reason, browserify is not recognizing the -o param.
Here is my workaround, but I'm not sure it's legit.:

```
package.json line 8:      "build": "browserify -t [ babelify --presets [ es2015 react ] ] src/app.js > build/app.js"
```

**Comment by jhartikainen** [comment]
@mukadder it seems I had a minor oversight and didn't add `simple-peer` and `simple-websocket` to the package.json file. https://github.com/jhartikainen/react-chat-app/commit/e0723b39e9256c93eeb45d6be849f0cdb6e1f161 fixes it, or you can fix it by doing `npm install --save simple-peer simple-websocket`

**Comment by jhartikainen** [comment]
@adampasz I'm not sure why the `-o` flag would not be recognized. It's still documented in Browserify, so it hasn't been removed or anything. If I had to guess, it might be related to whatever shell you're using to run the command.

Closing this issue as the original problem was solved.

**Comment by adampasz** [comment]
It's fixed now.  I guess browserify was failing because of the missing files.

**Comment by jhartikainen** [comment]
OK good to know :)
