### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hiteshtara** [jhartikainen/react-chat-app#2]
Hi there ,
I learn new technologies from evangelist like you who have posted  excellent blogs with exceptional quality codes which you have.But only problem is when I read documentation and run few commands I see happy ending(localhost:3000/apprunning ) which is not happening in your case.Please improve may be it needs some tweaks.
my system is ubuntu lts14 
node -v 4.4.3
npm -v 2.15.1

**Comment by jhartikainen** [comment]
Feel free to contribute if you have improvements. As it is a side project I'm doing in my free time, I can't provide support for every possible platform combination.
